name: MouBieShop

version: '${project.version}'
api-version: ${plugin.api.version}

authors: [ MouBieCat ]

depend: [ MouBieAPI ]
softdepend: [ Vault, PlayerPoints ]

main: com.cat.server.MouBieCat

commands:
  MouBieShop:
    description: "為該插件的主要指令。"
    aliases: [ mbs ]

permissions:
  MouBieShop.create:
    description: "是否可以創建店鋪或是商店。"

  MouBieShop.remove:
    description: "是否可以刪除店鋪或是商店。"

  MouBieShop.editor:
    description: "是否可以編輯店鋪或是商店。"
